[package]
name = "bourh/advanced-analytics"
description = ".."
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@2.0.1"